### PR TITLE
Overlay class

### PR DESCRIPTION
**Pull request by johnhwhite**
such as `ag-custom-component-popup`

### CODE REVIEW

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-overlay-class](https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-overlay-class)

**Review by Blackbaud-SteveBrush — COMMENTED** [review]
We should bump the version listed in `peerDependencies` for `@skyux/core` to the version that includes the `wrapperClass` property.

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-overlay-class](https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-overlay-class)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-overlay-class](https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-overlay-class)

**Review by Blackbaud-SteveBrush — APPROVED** [review]

**Pull request merged**
