### PR TITLE
Modern theme for date range picker

### PR DESCRIPTION
**Pull request by Blackbaud-AlexKingman**
https://blackbaud.invisionapp.com/console/share/UG1N3XTCC7/483432661/play?frame-cb=1609788344367

### CODE REVIEW

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-modern-theme-date-range-picker](https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-modern-theme-date-range-picker)

**Review by Blackbaud-ToddRoberts — DISMISSED** [review]

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-modern-theme-date-range-picker](https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-modern-theme-date-range-picker)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-modern-theme-date-range-picker](https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-modern-theme-date-range-picker)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-modern-theme-date-range-picker](https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-modern-theme-date-range-picker)

**Review by Blackbaud-SteveBrush — APPROVED** [review]

**Pull request merged**
