### PR TITLE
Add date pipe docs

### PR DESCRIPTION
**Pull request by Blackbaud-SteveBrush**
- First pass at some documentation for `SkyDatePipe`.

### CODE REVIEW

**Comment by Blackbaud-BobbyEarl** [comment]
Preview build at [https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-datepipe-docs](https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-datepipe-docs)

**Comment by Blackbaud-BobbyEarl** [comment]
Preview build at [https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-datepipe-docs](https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-datepipe-docs)

**Comment by Blackbaud-AdamFunderburk** [comment]
How would we state the usage guidelines for the date pipe in SKY UX? Is it as simple as "always use this whenever a date is displayed or entered in the UI"? Are there any circumstances where a SKY UX application _shouldn't_ use this for date values?

As far as demos/examples go, I don't have any research on the utility of the sort of "content formatting" tools that SKY provides. I see all of the examples of numeric on its documentation - do you think there's value in showing a small selection of those in the date pipe example?

**Comment by Blackbaud-AdamFunderburk** [comment]
If we took the path of adding some basic illustrative examples of the date pipe behavior, the demos could look something like this. Do we have any labels or "definitions" for the different formats?
image

**Comment by Blackbaud-BobbyEarl** [comment]
Preview build at [https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-datepipe-docs](https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-datepipe-docs)

**Comment by Blackbaud-BobbyEarl** [comment]
Preview build at [https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-datepipe-docs](https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-datepipe-docs)

**Comment by Blackbaud-BobbyEarl** [comment]
Preview build at [https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-datepipe-docs](https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-datepipe-docs)

**Pull request merged**
