### PR TITLE
Initialize the control value during a lifecycle hook

### PR DESCRIPTION
**Pull request by johnhwhite**

### CODE REVIEW

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-234-initialize-control-value](https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-234-initialize-control-value)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-234-initialize-control-value](https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-234-initialize-control-value)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-234-initialize-control-value](https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-234-initialize-control-value)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-234-initialize-control-value](https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-234-initialize-control-value)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-234-initialize-control-value](https://developer.blackbaud.com/skyux-datetime?_sp.spa=pr-234-initialize-control-value)

**Review by Blackbaud-AlexKingman — APPROVED** [review]

**Pull request merged**
